# Generated by Django 4.1.2 on 2024-07-10 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='id_autor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='id_libro', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('anio', models.IntegerField(max_length=4)),
                ('descripcion', models.CharField(max_length=200)),
                ('id_autor', models.ForeignKey(db_column='id_autor', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
            ],
        ),
    ]
