# Generated by Django 4.1.2 on 2024-07-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autor_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='anio',
            field=models.IntegerField(),
        ),
    ]
