# Generated by Django 4.1.2 on 2024-07-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_autor_libro_reconocido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_categorias',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
    ]
